export type SchoolLevel = 'podstawowa' | 'ponadpodstawowa'
export type SchoolClass = string

export interface ProgramPoint {
  id: string
  code: string
  description: string
  level: SchoolLevel
  class: SchoolClass
  subject: string
  zakres?: string
  dzialNazwa?: string
  dzialNumer?: string
  lpWDziale?: number
}

export interface TaskParameter {
  id: string
  name: string
  type: 'number' | 'integer' | 'text' | 'choice'
  min?: number
  max?: number
  step?: number
  options?: string[]
  value: number | string
  unit?: string
  isAutoDetected: boolean
}

export interface AnswerKeyItem {
  id: string
  answer: string
  points: number
  explanation?: string
}

export interface TaskSpecification {
  answerKeyMethod?: string
  answerKeyAnswer?: string
  answerKeyConclusions?: string
}

export type TaskType = 'open' | 'closed'

export interface TaskChoice {
  id: string
  /** Treść wariantu odpowiedzi; może zawierać placeholdery `{{paramId}}`. */
  content: string
  isCorrect: boolean
  /** Punkty za zaznaczenie tej odpowiedzi (domyślnie 1 jeśli isCorrect, 0 wpp.). */
  points?: number
  explanation?: string
}

export interface Task {
  id: string
  title: string
  content: string
  subject: string
  level: SchoolLevel
  class: SchoolClass
  programPoints: string[]
  categories?: string[]
  parameters: TaskParameter[]
  answerKey: AnswerKeyItem[]
  specification: TaskSpecification
  tags: string[]
  createdAt: number
  updatedAt: number
  /** True when the task was generated by an AI model (OpenRouter). */
  aiGenerated?: boolean
  /** ID of the model that generated the task (e.g. "anthropic/claude-3.5-sonnet"). */
  aiModel?: string
  /** Rodzaj zadania: 'open' (tradycyjne) lub 'closed' (ABCD). Brak = 'open'. */
  taskType?: TaskType
  /** Warianty odpowiedzi a, b, c, d (dla taskType === 'closed'). */
  choices?: TaskChoice[]
  /** Czy losowo mieszać kolejność wariantów podczas generowania. */
  shuffleChoices?: boolean
}

export interface Category {
  id: string
  name: string
  parentId: string | null
  position?: number
  color?: string
  createdAt: number
  updatedAt: number
}

export interface Test {
  id: string
  title: string
  description: string
  tasks: string[]
  settings: {
    shuffleTasks: boolean
    shuffleAnswers: boolean
    timeLimitMinutes: number | null
    showPoints: boolean
  }
  generatedAt: number
}

export interface RandomizedTask {
  originalTaskId: string
  title: string
  content: string
  parameters: TaskParameter[]
  /** Warianty po podstawieniu parametrów + opcjonalnym przemieszaniu kolejności. */
  choices?: TaskChoice[]
  taskType?: TaskType
}
